### ISSUE TITLE
Run the OVE Server on a VM (just clone this repo for now)

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#10]
The application launcher page of OVE should be visible and it should be possible to launch new OVE applications.

**Comment by dandavies99** [comment]
Some success with this: The OVE homepage can be viewed on the test server (internal/VPN) at https://liionsden.rcs.ic.ac.uk/.

Unfortunately, none of the subpages are visible e.g. https://liionsden.rcs.ic.ac.uk/ui/launcher to launch applications and https://liionsden.rcs.ic.ac.uk/ui/status to see the status of running OVE components.

I strongly suspect this is because we are using Caddy but OVE uses nginx already. We may be able to modify the `Caddyfile` to fix this, but it might be better overall to look into doing away with Caddy and just using nginx, modifying `.config/default.conf` accordingly.

**Comment by AdrianDAlessandro** [comment]
I should say that I am also having trouble viewing those subpages locally. I tried to get to the ui launcher and it just didn't work

**Comment by dandavies99** [comment]
When running locally, I've found that clearing the browser cache or using an incognito page has worked for viewing the ui launcher. Also running `docker volume prune` and `docker network prune` if changing any config.

**Comment by AdrianDAlessandro** [comment]
I needed to destroy all my images and re-build them and it got there

**Comment by dandavies99** [comment]
I think we can close this issue now. Basically OVE itself is running fine on the VM: you should be able to navigate to http://liionsden.rcs.ic.ac.uk:8080 and http://liionsden.rcs.ic.ac.uk:8080/ui/launcher. See example screenshots below. 

Only nginx is required, not caddy. 

After getting nginx itself to output more detailed logs, it turned out that the problems were arising from incorrectly configuring nginx to handle https requests. This will take some fixing, so **I'll open a separate issue now with much more detail** because ultimately we want to handle https requests. For now though, the server is not configured for https://... with ssl, so only http://... will work.

I will submit a PR before we close the issue, but it'll just be a bit of extra info in the README on the VM configuration. 

OVE application launcher page:

![Screenshot 2023-01-25 at 11 41 49](https://user-images.githubusercontent.com/5871253/214554717-ad5663c3-f264-4931-8968-0bb841634680.png)

Preview of OVE space and section with HTML app: 

![Screenshot 2023-01-25 at 11 44 36](https://user-images.githubusercontent.com/5871253/214555221-6793e264-d098-4120-8cb4-25c04535cd99.png)
